### PR TITLE
Add link to service info on service notifications. New argument cgiurl.

### PR DESCRIPTION
**Pull request by 48kRAM**
For service notifications, add a link to the nagios service info page to the mattermost message.

Requires passing the new command-line argument '--cgiurl' to point to your nagios instance's extinfo.cgi.

### CODE REVIEW

**Comment by andrefreitas** [comment]
Hi,
Sorry, I believe I missed the notification for this PR :/ 

 I refactored the code in master. Can you merge master into your branch to author this PR?

Thanks!

**Comment by 48kRAM** [comment]
Sorry - I've been on vacation for a while and didn't see this until
yesterday.

I can still refactor this and re-submit the PR if you'll still accept it.

-Josh

**Comment by andrefreitas** [comment]
Hi, yes you are welcome! I am reopening the PR.

**Comment by 48kRAM** [comment]
Closing this PR - will re-submit a new one based on your refactored code. No point in tracking a merge from code that I never put out in the wild.

**Pull request closed without merging**
