### PR TITLE
add emojis

### PR DESCRIPTION
**Pull request by revol**
quick & dirty emoji support

### CODE REVIEW

**Comment by andrefreitas** [comment]
Hi @revol , thanks for your pull request.

I am wondering if emojis can be turned by an optional flag --emoji. Can you give me some screenshots to see how they look like with the notifications?

**Comment by richilp** [comment]
Hi there,

I just installed a few minutes ago.
It looks like this:
borrar

**Comment by andrefreitas** [comment]
@richilp thanks! This is actually a good way of giving a visual clue since Mattermost provides no way of changing the border color of notifications like this one: 

image

Thanks for your pull request @revol, I have just merged

**Comment by revol** [comment]
Full Set of emojis:
Full List

**Pull request merged**
